"""
file_parser.py

Step 1 of the pipeline:
  - Read each .xlsx file into a Pandas DataFrame
  - Apply the 3-case REPORT TIME resolution (PRD Section 2 / Backend Logic Section 1 & 2)
  - Convert all NaN values to None (Python) for safe downstream handling

REPORT TIME Resolution Rules:
  CASE 1: Both files have REPORT TIME → they MUST match → else ERROR
  CASE 2: Only one file has REPORT TIME → copy to the file that is missing it
  CASE 3: Neither file has REPORT TIME → use MAX(STTS TIME) across all rows
"""

import io
import math
import zipfile
import pandas as pd
from fastapi import HTTPException
from utils.validators import validate_columns
from utils.time_utils import parse_datetime_str, to_ist, IST, format_ist


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _safe_val(v):
    """Convert NaN / NaT / inf to None. Everything else passes through."""
    if v is None:
        return None
    try:
        if pd.isnull(v):
            return None
    except (TypeError, ValueError):
        pass
    if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
        return None
    return v


def _strip_styles_from_xlsx(raw_bytes: bytes) -> bytes:
    """
    Replaces the 'xl/styles.xml' in the Excel zip archive with a minimal valid stylesheet.
    This strips out all custom formatting, which bypasses openpyxl parsing bugs (like Fill errors).
    """
    minimal_styles = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">\n'
        '  <fonts count="1"><font><sz val="11"/><name val="Calibri"/><family val="2"/></font></fonts>\n'
        '  <fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills>\n'
        '  <borders count="1"><border><left/><right/><top/><bottom/></border></borders>\n'
        '  <cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>\n'
        '  <cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/></cellXfs>\n'
        '  <cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>\n'
        '  <dxfs count="0"/>\n'
        '  <tableStyles count="0" defaultTableStyle="TableStyleMedium2" defaultPivotStyle="PivotStyleLight16"/>\n'
        '</styleSheet>'
    )
    
    in_buf = io.BytesIO(raw_bytes)
    out_buf = io.BytesIO()
    
    try:
        with zipfile.ZipFile(in_buf, "r") as zin:
            with zipfile.ZipFile(out_buf, "w", zipfile.ZIP_DEFLATED) as zout:
                for item in zin.infolist():
                    if item.filename == "xl/styles.xml":
                        # Write our minimal valid stylesheet instead of the corrupted one
                        zout.writestr(item.filename, minimal_styles)
                    else:
                        # Copy the other files as-is
                        zout.writestr(item, zin.read(item.filename))
        return out_buf.getvalue()
    except Exception:
        # If any zip manipulation fails, fall back to the original bytes
        return raw_bytes


def _has_report_time(df: pd.DataFrame) -> bool:
    """Return True if the DataFrame has at least one non-null REPORT TIME value."""
    if "REPORT TIME" not in df.columns:
        return False
    return df["REPORT TIME"].notna().any()


def _get_report_time_value(df: pd.DataFrame):
    """Return the first non-null REPORT TIME value as an IST-aware datetime, or None."""
    if "REPORT TIME" not in df.columns:
        return None
    non_null = df["REPORT TIME"].dropna()
    if non_null.empty:
        return None
    val = non_null.iloc[0]
    return to_ist(val)


def _get_max_stts_time(dfs: list) -> object:
    """
    CASE 3: Return MAX(STTS TIME) across all DataFrames as IST-aware datetime.
    Returns None if no valid STTS TIME found.
    """
    max_dt = None
    for df in dfs:
        if "STTS TIME" not in df.columns:
            continue
        for raw_val in df["STTS TIME"].dropna():
            dt = to_ist(raw_val)
            if dt is None:
                continue
            if max_dt is None or dt > max_dt:
                max_dt = dt
    return max_dt


def _find_header_row(bytes_buf: io.BytesIO) -> int:
    """
    Scan the first 5 rows of an Excel file to find which row contains the
    actual column headers (i.e. rows that have known column names like
    'ZONE', 'STTS CODE', 'RAKE NAME').

    Returns the 0-based row index to use as the header, defaulting to 0.
    Files generated by automation tools (e.g. FOIS) often have a title row
    like 'INSIGHT DETAILS' above the real headers.
    """
    ANCHOR_COLS = {"ZONE", "STTS CODE", "RAKE NAME", "STTS TIME"}
    try:
        df_raw = pd.read_excel(bytes_buf, header=None, nrows=5, engine="openpyxl")
    except Exception:
        return 0

    for row_idx in range(len(df_raw)):
        row_vals = {str(v).strip().upper() for v in df_raw.iloc[row_idx].tolist() if pd.notna(v)}
        # If the majority of anchor columns are present in this row, it's the header
        if len(ANCHOR_COLS & row_vals) >= 3:
            return row_idx
    return 0


# ─── Main parser ──────────────────────────────────────────────────────────────

def parse_files(file_bytes_list: list) -> tuple:
    """
    Parse a list of (filename, bytes) tuples into DataFrames.
    Apply REPORT TIME resolution.
    Return (list_of_dataframes, resolved_report_time_ist_aware_datetime).

    Raises HTTPException on validation failures.
    """
    dfs = []
    filenames = []

    for filename, raw_bytes in file_bytes_list:
        # ── Step 1: Try reading the file (heal corrupt styles if needed) ─────
        try:
            readable_bytes = raw_bytes
            pd.read_excel(io.BytesIO(readable_bytes), engine="openpyxl", nrows=1)
        except Exception:
            # Style sheet is corrupted — strip and replace with minimal stylesheet
            readable_bytes = _strip_styles_from_xlsx(raw_bytes)

        # ── Step 2: Auto-detect header row (handle title rows like 'INSIGHT DETAILS') ──
        header_row = _find_header_row(io.BytesIO(readable_bytes))

        # ── Step 3: Read the full DataFrame with the correct header row ──────
        try:
            df = pd.read_excel(io.BytesIO(readable_bytes), engine="openpyxl", header=header_row)
        except Exception as e:
            raise HTTPException(status_code=400, detail=f"Cannot read file '{filename}': {str(e)}")

        # Strip whitespace from column names
        df.columns = [str(c).strip() for c in df.columns]

        # Validate required columns
        validate_columns(df, filename)

        dfs.append(df)
        filenames.append(filename)

    # ── REPORT TIME resolution ────────────────────────────────────────────────
    resolved_times = []
    for df in dfs:
        if _has_report_time(df):
            resolved_times.append(_get_report_time_value(df))
        else:
            resolved_times.append(None)

    active_times = [t for t in resolved_times if t is not None]

    if active_times:
        # All files containing a REPORT TIME must match (within 1-minute drift)
        base = active_times[0]
        for i, t in enumerate(resolved_times):
            if t is not None:
                diff = abs((base - t).total_seconds())
                if diff > 60:  # allow up to 1-minute drift
                    raise HTTPException(
                        status_code=400,
                        detail=(
                            f"REPORT TIME mismatch between files. "
                            f"Expected {format_ist(base)} but '{filenames[i]}' has {format_ist(t)}. "
                            f"All uploaded files must share the same REPORT TIME."
                        )
                    )
        resolved_report_time = base
        # Copy to those files that are missing it
        for i, t in enumerate(resolved_times):
            if t is None:
                dfs[i]["REPORT TIME"] = base

    else:
        # CASE 3: No file has REPORT TIME — use MAX(STTS TIME)
        resolved_report_time = _get_max_stts_time(dfs)
        if resolved_report_time is None:
            raise HTTPException(
                status_code=400,
                detail="No REPORT TIME found in any file and no valid STTS TIME to fall back on."
            )
        for i in range(len(dfs)):
            dfs[i]["REPORT TIME"] = resolved_report_time

    return dfs, resolved_report_time, filenames